CHANGELOG.md
README.md
examples/multi-bot/README.md
examples/multi-bot/app.js
examples/simple-bot/README.md
examples/simple-bot/simple-bot-slack.js
lib/middleware/index.js
test/test.middleware_receive.js

Allow configs to be passed in to middleware require function with:
```js
var watsonMiddleware = require('botkit-middleware-watson')({
username: YOUR_CONVERSATION_USERNAME,
password: YOUR_CONVERSATION_PASSWORD,
workspace_id: YOUR_WORKSPACE_ID,
version_date: '2016-09-20'
});
```

Change the way configs are passed

---

lib/middleware/index.js
lib/middleware/utils.js

When error occurs in underlying watson files, it only gets displayed as “Error: {}”.
This makes errors displayed in a more elaborate way.
Also, this fixes a issue where after() function never got the watsonResponse object back to it.

Actually displaying errors.

---

CHANGELOG.md
README.md
examples/simple-bot/simple-bot-slack.js
lib/middleware/index.js
lib/middleware/utils.js

This reduces the number of calls made to Conversation by calling a new function in the middleware in the `hears` event handler. Also fixes issue #20

Add another function to middleware for Conversation API calls

---

lib/middleware/index.js

Switch order of calls to allow users to change the response object in the after callback.
Check #24

Fix order of calls

---

lib/middleware/utils.js
package.json
test/test.context_store.js

readContext didn't check if storage returned error
updateContext called callback without waiting for storage to finish

Fixed error handling in readContext and updateContext functions

---

lib/middleware/index.js

Without return the code below `next()` is executed.
This is a bugfix for the actual bug,
but I still want a proper solution for #61.

Don't send empty messages to watson

---

lib/middleware/index.js

It is a yet another alias to middleware.receive function.
I think that it improves code readability in use cases like sending action results to Watson.
Please look at examples in https://github.com/watson-developer-cloud/botkit-middleware/pull/66/commits/f68a46d1ce0f47c3484d67febd508a068da49e88#diff-04c6e90faac2675aa89e2176d2eec7d8R165

Added sendToWatson function

---

lib/middleware/utils.js
test/test.context_store.js

My bot started failing after updating middleware from master branch and then I realized that it wasn't a great idea to handle storage error in readContext.
Error is returned when there is nothing stored yet, so existing users can keep talking but new users get error on every message.

Ignore storage error in readContext

---

CHANGELOG.md
lib/middleware/utils.js
test/test.context_store.js

Before this patch updateContext ignored other fields in storage
and assigned properties of previous context as top level properties in storage.
Earlier attempt to fix storage: #7 
`TypeError: Converting circular structure to JSON`: https://github.com/watson-developer-cloud/botkit-middleware/issues/71#issuecomment-312506143
I fixed this issue because circular structure error started happening in my project again.

updateContext actually preserves other data stored in users storage

---

CHANGELOG.md
lib/middleware/utils.js
test/test.context_store.js

Oops, I did it again.
Sorry for breaking updateContext, it should be good now.
My bot was working with BotMock after previous update, so I hadn't tested it manually.

[Critical] updateContext fails on the first write for a new user when simple storage is used

---

lib/middleware/index.js
test/test.middleware_receive.js

Welcome message is not allowed to contain any input [by definition](https://console.bluemix.net/docs/services/conversation/dialog-build.html#dialog-build), but watson receive middleware ignores all empty messages.
This patch allows to use empty message with type=welcome to indicate welcome event in Watson Conversation.
Example with Sockets connector:
```js
controller.on('hello', function(bot, message) {
message.type = 'welcome';
watsonMiddleware.sendToWatsonAsync(bot, message).catch(function (error) {
console.log('Error', error);
}).then(function () {
return handleWatsonResponse(bot, message);
});
});
controller.on('message_received', handleWatsonResponse);
```
Fixes #61

Support for welcome event

---

README.md
lib/middleware/index.js
package.json
test/test.middleware_send_to_watson.js

This feature simplifies updating context and sending it to Conversation.
I have used it in my bot already and it works as I wanted it to.
receive and interpret methods are not affected
change is backwards compatible with calling sendToWatson without contextDelta.
I ordered "implementing app actions" sections in decreasing chronological order (also in decreasing order of usability).
Closes #91

Added contextDelta parameter to sendToWatson method

---

examples/simple-bot/.env

Because dotenv library does not support end of line comments,
only full line comments are supported.
This will help to avoid issues like https://github.com/watson-developer-cloud/botkit-middleware/issues/99#issuecomment-331674925

Remove end of line comments from .env in simple-bot

---

examples/multi-bot/.env

Removed end of line comments (#US-SOUTH) from .env in multi-bot
PR for issue #105 @Naktibalda

Removed end of line comments from .env in multi-bot

---

CHANGELOG.md
lib/middleware/index.d.ts

I forgot to update signatures of methods that I no longer use when I renamed botkit to Botkit.
So I fixed them now.
@germanattanasio how come 1.6.0 hasn't been published to [npm](https://www.npmjs.com/package/botkit-middleware-watson)?

Fixed function signatures in Typescript definition file

---

examples/multi-bot/package.json
examples/simple-bot/package.json

Updated Botkit-middleware version to 1.6.1 in both simple-bot & multi-bot to leverage latest features

Updated Botkit-middleware version in examples 

---

lib/middleware/index.js
test/test.middleware_receive.js

Text can not contain the following characters: tab, new line, carriage return.
Fixes #102
Fixes #116

Replace not-permitted characters in message text

---

examples/multi-bot/bot-facebook.js
examples/multi-bot/bot-slack.js
examples/multi-bot/bot-twilio.js
examples/simple-bot/simple-bot-slack.js

I think this should fix issue #125 : adding extra checks in the examples, that implement more graceful error handling, for future users to base their code on. (Not sure if there is a JSON Schema of the Watson Conversation message format somewhere that would allow for more finegrained compliance checking?)

Fix issue #125

---

README.md
examples/multi-bot/.env
examples/multi-bot/bot-slack.js
examples/simple-bot/.env
examples/simple-bot/simple-bot-slack.js

Slack currently complains that this is missing when initiating connections

Make use of the Slack signing secret in the sample bots

---

lib/middleware/index.d.ts

Exports `WatsonMiddleware` so 3rd party code can make use of these type definitions.
I also moved the `Payload` and `ContextDelta` interfaces to be in the `Middleware` interface, should not be a breaking change since they weren't exported previously.

Export WatsonMiddleware typescript definition for re-use

---

lib/middleware/index.d.ts

Reverts watson-developer-cloud/botkit-middleware#165
It broke existing consumers and didn't work as intended.
@rob-pocklington-a139759 agrees that this change can be reverted.

Revert "Export WatsonMiddleware typescript definition for re-use"
